startdust_website/panel/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.auth.decorators import login_required
from panel.views import IndexView

urlpatterns = patterns('',
    url(r'^$', login_required(IndexView.as_view()), name='panel-index'),
    url(r'^projects/(?P<id_project>\d+)/$', 'panel.views.show_project', name='project'),
    url(r'^projects/add/', 'panel.views.add_project', name='add-project'),
	url(r'^projects/(?P<id_project>\d+)/delete/$', 'panel.views.remove_project', name='delete-project'),
    url(r'^projects/(?P<id_project>\d+)/update/$', 'panel.views.change_project', name='update-project'),
    url(r'^projects/(?P<id_project>\d+)/error/(?P<id_error>\d+)/$', 'panel.views.show_error', name='error'),
    url(r'^projects/(?P<id_project>\d+)/error/(?P<id_error>\d+)/similar/$', 'panel.views.show_similar_errors', name='similar-errors'),
    url(r'^projects/(?P<id_project>\d+)/request/(?P<day>\d+)/(?P<month>\d+)/(?P<year>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/$',
       'panel.views.show_requests',
       name='show-requests'),
)

startdust_website/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from home.views import IndexView, DocsView, FeaturesView


urlpatterns = patterns('',
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^docs/$', DocsView.as_view(), name='docs'),
    url(r'^features/$', FeaturesView.as_view(), name='features'),

    (r'^api/', include('api.urls')),
    (r'^panel/', include('panel.urls')),
    (r'^accounts/', include('registration.backends.default.urls')),
    (r'^auth/', include('registration.auth_urls')),
)

urlpatterns += staticfiles_urlpatterns()

startdust_website/projects/models.py
from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    name = models.CharField(max_length=50)
    url = models.URLField(verify_exists=False)
    token = models.CharField(max_length=255)
    user = models.ManyToManyField(User, null=True, blank=True)

    def get_absolute_url(self):
        return '/panel/projects/%d/' % self.id

startdust_website/responses/models.py
from django.db import models
from datetime import datetime
from projects.models import Project

class Response(models.Model):

    time = models.FloatField()
    url = models.URLField(verify_exists=False)
    date = models.DateTimeField(null=True, editable=False)
    project = models.ForeignKey(Project, null=True, editable=False) #will be change this

    class Meta:
        ordering = ['date']

    def save(self, *args, **kwargs):
        date = datetime.now()
        self.date = datetime(date.year, date.month, date.day, date.hour, date.minute)
        super(Response, self).save(*args, **kwargs)

startdust_website/projects/forms.py
from uuid import uuid4
from django.forms import ModelForm
from projects.models import Project


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        exclude = ('token', 'user')

class UpdateProjectForm(ModelForm):
    class Meta:
        model = Project
        exclude = ('token')

startdust_website/panel/views.py
from uuid import uuid4
from django.views.generic import TemplateView
from django.template.response import TemplateResponse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Max, Avg
from projects.forms import ProjectForm, UpdateProjectForm
from projects.models import Project
from errors.models import Error
from requests.models import Request
from responses.models import Response

import calendar


class IndexView(TemplateView):
    template_name = 'panel/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['projects'] = Project.objects.filter(user=self.request.user)
        return context


@login_required
def show_project(request, id_project):
    project = get_object_or_404(Project, id=id_project)
    errors = Error.objects.filter(project=project.id).values('exception', 'url').annotate(Count('url'), Max('id'))
    average_responses = Response.objects.filter(project=project.id).values('url').annotate(Avg('time'))
    average_responses_by_date = Response.objects.filter(project=project.id).values('date').annotate(Avg('time'))
    requests = Request.objects.filter(project=project.id).values('date').annotate(quant=Count('url'))
    
    for item in average_responses_by_date:
        item['date'] = calendar.timegm(item['date'].timetuple()) * 1000

    for item in requests:
        item['date'] = calendar.timegm(item['date'].timetuple()) * 1000

    context = {
        'project': project, 
        'errors': errors, 
        'requests': requests,
        'average_responses': average_responses,
        'average_responses_by_date': average_responses_by_date,
    }

    return TemplateResponse(request, 'panel/project.html', context)


@login_required
def add_project(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST)

        if form.is_valid():
            form.instance.token = str(uuid4())
            instance = form.save()
            instance.user.add(request.user)
            return HttpResponseRedirect('/panel/projects/%d' % form.instance.id)

    else:
        form = ProjectForm()

    return TemplateResponse(request, 'panel/project_form.html', {'form': form})

@login_required
def remove_project(request, id_project):
    get_object_or_404(Project, id=id_project).delete()
    return HttpResponseRedirect('/panel/')

@login_required
def change_project(request, id_project):
    project = get_object_or_404(Project, id=id_project)

    if request.method == 'POST':
        form = UpdateProjectForm(request.POST, instance=project)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/panel/projects/%d/' % form.instance.id)
    else:
        form = UpdateProjectForm(instance=project)

    return TemplateResponse(request, 'panel/project_form.html', {'form': form})

@login_required
def show_error(request, id_project, id_error):
    error = get_object_or_404(Error, id=id_error)
    return TemplateResponse(request, 'panel/error.html', {'error': error})

@login_required
def show_similar_errors(request, id_project, id_error):
    error = get_object_or_404(Error, id=id_error)
    similar_errors = Error.objects.filter(url=error.url, exception=error.exception).exclude(id=error.id)
    return TemplateResponse(request, 'panel/similar_errors.html', {'errors': similar_errors})

@login_required
def show_requests(request, id_project, day, month, year, hour, minute):
    requests = Request.objects.filter()
    return TemplateResponse(request, 'panel/requests.html', {'requests': requests})

startdust_website/panel/templates/panel/base.html
<!doctype html>
<html>
    <head>
        <title>stardust</title>
        <link rel="stylesheet" href="/static/css/reset.css" type="text/css" />         
        <link rel="stylesheet" href="/static/css/grid.css" type="text/css" /> 
        <link rel="stylesheet" href="/static/css/style.css" type="text/css" />    
        <link rel="stylesheet" href="/static/css/panel.css" type="text/css" />
        {% block form %}{% endblock %}    
    </head>
    {% block flot %} {% endblock %}
    <body>
        <div class="bar"></div>
        <div class="header">
            <div class="row">
                <div class="column grid_12">
                    <h1><a href="/">stardust</a></h1>
                </div>
            </div>
        </div>
        <div class="menu">
            <div class="row">
                <div class="column grid_12">
                    <div class="user">Hi {{ request.user }}</div>
                    <ul>
                        <li><a href="/panel/">your projects</a></li>
                        <li><a href="/accounts/password/change/">edit account</a></li>
                        <li><a href="/auth/logout/">logout</a></li>
                    </ul>               
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="column grid_12">
                    {% block content %}{% endblock %}
            </div>
        </div>
        <div class="footer-panel">
            <div class="row">
                <div class="column grid_12">
                    <p>© 2011-2011</p>
                </div>
            </div>
        </div>
    </body>
</html>

startdust_website/panel/templates/panel/error.html
{% extends "panel/base.html" %}

{% block content %}
	<div class="container">
            <div class="project">
                  <div class="row">
                        <div class="column grid_9">
                              <h2> {{ error.project.name }}: {{ error.exception }}</h2>
                        </div>
                        <div class="column grid_3">
                              <div class="button similar-errors">
                                    <a href="/panel/projects/{{ error.project.id }}/error/{{ error.id }}/similar/">similar errors</a>
                              </div>
                        </div>
                  </div>
                  <div class="row">
                        <div class="column grid_12">
                              <ul>
                              	<li><p>{{ error.date }}</p></li>
                              	<li><p>{{ error.url}}</p></li>
                              	<li><p>{{ error.traceback }}</p></li>
                              	<li><p>{{ error.exception }}</p></li>
                              </ul>
                        </div>
                  </div>		
		</div>
            <div class="clear"></div>
            <div class="clear"></div>
	</div>
{% endblock %}

startdust_website/panel/templates/panel/index.html
{% extends "panel/base.html" %}

{% block content %}
<div class="container">
	<h2>Panel Applications</h2>

    {% if projects %}
	<div class="projects">
        <h3>Your projects</h3>
        <ul>
            {% for project in projects %}
                <li>
                    <a href="{% url project project.id %}">
                        <p><span>Project name: </span>{{ project.name}}</p>
                        <p><span>URL: </span>{{ project.url}}</p>
                    </a>
                    <p><span>Token: </span>{{ project.token }}</p>
                </li>
            {% endfor %}
        </ul>
	</div>
    {% else %}
        Add a project please
    {% endif %}

	<div class="button">
		<a href="/panel/projects/add/">Add your project</a>
	</div>
    <div class="clear"></div>
    <div class="clear"></div>
</div>
{% endblock %}

startdust_website/panel/templates/panel/project.html
{% extends "panel/base.html" %}

{% block flot %}
    <!--[if lte IE 8]>
        <script language="javascript" type="text/javascript" src="/static/js/excanvas.min.js"></script>
    <![endif]-->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.js" type="text/javascript"></script>
    <script src="/static/js/jquery.flot.js" type="text/javascript" language="javascript"></script>
    <script>
       $(function () {
             var response = [{% for response in average_responses_by_date %}[{{ response.date }}, {{ response.time__avg }}]{% if not forloop.last %},{% endif %}{% endfor %}];

             var request = [{% for request in requests %}[{{ request.date }}, {{ request.quant }}]{% if not forloop.last %},{% endif %}{% endfor %}];

            $.plot($("#response-time"), [response], {
                xaxis: {
                    mode: "time",
                    timeformat: "%m/%d %H:%M"
                }
            });

            $.plot($("#request-time"), [request], {
                xaxis: {
                    mode: "time",
                    timeformat: ""
                }
            });
       });

    </script>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="project">
            <h2>{{ project.name }}</h2>
            <p>URL: <span><a href="{{ project.url }}" target="_blank">{{ project.url }}</a></span></p>
            <div class="line"></div>
            <div class="row">
                <div class="column grid_8">
                    <p>Average response time (for all urls) min milliseconds</p>
                    <div id="response-time" class="response-graph"></div>
                </div>
                <div class="column grid_4">
                    <p>request/min</p>
                    <div id="request-time" class="request_graph"></div>
                </div>
            </div>
            <div class="row">
                <div class="column grid_6">
                    <div class="line grid_6"></div>
                    {% if errors %}
                    <p>Errors:</p>
                    <ul>
                        {% for error in errors %}
                        <li><a href="/panel/projects/{{ project.id }}/error/{{ error.id__max }}/">{{ error.exception }} - {{ error.url }} - {{ error.url__count }}</a></li>
                        {% endfor %}
                    </ul>
                    {% else %}
                        <p>0 errors<p>
                    {% endif %}
                </div>
                <div class="column grid_6">
                    <div class="line grid_6"></div>
                    {% if project.response_set.all %}
                        <p>Average response time by url:</p>
                        <ul>
                            {% for response in average_responses %}
                                <li>{{ response.url }} - {{ response.time__avg }}ms</li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p>0 responses</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}
 

startdust_website/panel/templates/panel/project_form.html
{% extends "panel/base.html" %}

{% block form %}
	<link rel="stylesheet" href="/static/css/form.css" type="text/css" />
{% endblock %}

{% block content %}
<div class="container">
	<h2>Add your project</h2>
	<div class="form">
	    <form method="post" action="">
	    	{% csrf_token %}
	    	{{ form.as_p}}
	        <p><input type="submit" value="Add project" /></p>
	    </form>
    </div>
    <div class="clear"></div>
    <div class="clear"></div>
</div>
{% endblock %}

startdust_website/panel/templates/panel/similar_errors.html
{% extends "panel/base.html" %}

<!-- {% for error in errors %}
    {{error.date}}
    {{error.url}}
    {{error.traceback}}
    {{error.exception}}
{% endfor %} -->

{% block content %}
	<div class="container">
	    <div class="project">
	     	<h2> {{ errors.0.project.name }}</h2>
	      	{% for error in errors %}
	      	<a href="{{ error.get_absolute_url }}">
		      	<ul class="similar-errors">
			      	<li>{{ error.date }}</li>
			      	<li>{{ error.url}}</li>
			      	<li>{{ error.traceback }}</li>
			      	<li>{{ error.exception }}</li>
		      	</ul>
	      	</a>
	      	{% endfor %}
		</div>
	    <div class="clear"></div>
	    <div class="clear"></div>
	</div>
{% endblock %}